name: Update Ximalaya New Content

on:
  schedule:
    - cron: '0 14 * * *'   # 每天下午2点执行
  workflow_dispatch:      # 支持手动触发

jobs:
  update_txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_ximalaya.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add new_updates.txt
            git commit -m "Update new Ximalaya content"
            git push
          else
            echo "No new updates."
          fi
